### ISSUE TITLE
Crashes app when backgrounded on iOS

### ISSUE THREAD

**Issue by BWhiteApps** [FlutterPlaza/no_screenshot#1]
This package causes my iOS app to crash in the background with an exc_bad_access error:

'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=2, address=0x16b95bf70)
    frame #0: 0x00000001d3767e38 UIKitCore`-[UIView(Internal) _presentationControllerToNotifyOnLayoutSubviews] + 4
UIKitCore`-[UIView(Internal) _presentationControllerToNotifyOnLayoutSubviews]:

This error is resolved when I remove the no_screenshot package from my app.

One thing to note is that it crashes on background even if it isn't being used with AppLifecycleState.

**Comment by MrShafqatNadeem** [comment]
I have got the same issue, it crashes my app after a while. erroring that app consumes so much space,
XPC connection interrupted
* thread #1, queue = 'com.apple.main-thread', stop reason = EXC_RESOURCE RESOURCE_TYPE_MEMORY (limit=2098 MB, unused=0x0)
    frame #0: 0x00000001d061016c libsystem_malloc.dylib`small_free_list_add_ptr + 268
libsystem_malloc.dylib`small_free_list_add_ptr:
->  0x1d061016c <+268>: strb   w13, [x2, #0x8]
    0x1d0610170 <+272>: str    xzr, [x2]
    0x1d0610174 <+276>: eor    x13, x9, x0
    0x1d0610178 <+280>: eor    x12, x13, x12
Target 0: (Runner) stopped.

**Comment by fonkamloic** [comment]
Thank you, @BWhiteApps  and @MrShafqatNadeem, for raising this issue.

We will be pushing a fix by the end of the day.

**Comment by fonkamloic** [comment]
Issue fixed. https://pub.dev/packages/no_screenshot

Thank you again for your contributions
