### ISSUE TITLE
Unable to disable screen recording on iOS

### ISSUE THREAD

**Issue by riscait** [FlutterPlaza/no_screenshot#20]
Thank you for the convenient package.

The feature says "Disables screenshot and screen recoding on Android and iOS" but I could not disable screen recording on iOS.
On Android, the screen can be disabled and a black video is saved.

Is disabling screen recording on iOS planned to be implemented?
Or am I using it incorrectly?

**Comment by Riscait** [comment]
@fonkamloic 
Thanks for the reply.
We checked with iOS 16.3.1, which is currently the latest version. The "ScreenProtectorKit" that seems to be used in the iOS version has screen recording detection (screenProtectorKit.screenIsRecording), but does not seem to have a function to prohibit screen recording. Is there something running in a separate file?

https://github.com/FlutterPlaza/no_screenshot/blob/7bbd24e581a85c64d21deb86a4eea9ae51a2f443/ios/Classes/SwiftNoScreenshotPlugin.swift#L60-L62

[ScreenProtectorKit](https://github.com/prongbang/ScreenProtectorKit)

**Comment by fonkamloic** [comment]
@riscait  try again with this [upgrade](https://pub.dev/packages/no_screenshot/versions/0.0.1+7) or higher
