### ISSUE TITLE
Able to take screenshots after app is resumed fro background

### ISSUE THREAD

**Issue by Kronos-2701** [FlutterPlaza/no_screenshot#21]
I used this package to prevent screenshots in my flutter app . 
In ios after the app is sent to background , a message pops in the debug console .
message => 
[iOS][Snapshotting] Snapshotting a view that has not been rendered at least once requires afterScreenUpdates:YES.

and when the app is resumed , I was able to take screenshots.
After restarting everything was normal again.

**Comment by oncleguigs** [comment]
Faced the same issue. Did not find a better option than adding it in the didChangeAppLifecycleState

`AppLifecycleState? _notification; 
  @override
  void didChangeAppLifecycleState(AppLifecycleState state) {
      case AppLifecycleState.resumed, :
         _noScreenshot.screenshotOff();
        break;
      case AppLifecycleState.inactive:
         _noScreenshot.screenshotOff();
        break;
      case AppLifecycleState.paused:
        _noScreenshot.screenshotOff();
        break;
      case AppLifecycleState.detached:
        print("app in detached");
        break;
    }
  }`

**Comment by fonkamloic** [comment]
@Kronos-2701 What @oncleguigs  did is correct and how it should be used.
