### ISSUE TITLE
Error chanel

### ISSUE THREAD

**Issue by NathanFlorins** [FlutterPlaza/no_screenshot#22]
![image](https://user-images.githubusercontent.com/91219231/229756573-3f151b47-b5b8-4a9f-9432-6dbed9ff0a20.png)
I have this error that I don't understand

**Comment by ahmedradwan18** [comment]
did you find a solution?

**Comment by fonkamloic** [comment]
@ahmedradwan18 @NathanFlorins  Please provide steps to reproduce error. 

Try again with this [upgrade](https://pub.dev/packages/no_screenshot/versions/0.0.1+7) or higher
