### ISSUE TITLE
IOS 17 plugin not working

### ISSUE THREAD

**Issue by Harpreetcompetent** [FlutterPlaza/no_screenshot#23]
In Ios I am not able to  disable screenshot. Please add support for ios 17

**Comment by dgofactory** [comment]
It needs to update the ios ScreenProtectorKit pod to 1.3.* ! You could fork the repo for update and verify!

**Comment by fonkamloic** [comment]
@dgofactory @Harpreetcompetent   try again with this [upgrade](https://pub.dev/packages/no_screenshot/versions/0.0.1+7) or higher
