### ISSUE TITLE
iOS Screen recording and Screenshot Prevention Not Working: What's the Issue?

### ISSUE THREAD

**Issue by Matignaciom** [FlutterPlaza/no_screenshot#28]
Hello! I've noticed that it works perfectly on Android, but on iOS it's a different story. It doesn't prevent screenshots or screen recordings. Is there no support for that?

**Comment by darshil-di** [comment]
Do not used this

**Comment by fonkamloic** [comment]
@Matignaciom  try again with this [upgrade](https://pub.dev/packages/no_screenshot/versions/0.0.1+7) or higher
