### ISSUE TITLE
In iOS  screenshot is still working

### ISSUE THREAD

**Issue by ilyasarafathemvigo** [FlutterPlaza/no_screenshot#35]
Able to take screenshot in iphone 14  with double tap. 
am using latest package  no_screenshot 0.2.0

**Comment by akhil-ambady-ibs** [comment]
Same here

**Comment by kpitroda** [comment]
iPhone XR it's not working. By double tap backside I'm able to take screenshot.

**Comment by fonkamloic** [comment]
@kpitroda @akhil-ambady-ibs @akhil-ambady-ibs 

Could you please specify what iOS version each of you is using?

**Comment by fonkamloic** [comment]
@kpitroda @ilyasarafathemvigo @akhil-ambady-ibs


 @kefeh Can you please text this https://pub.dev/packages/no_screenshot/versions/1.0.0-beta.2

**Comment by ilyasarafathemvigo** [comment]
@

> @kpitroda @ilyasarafathemvigo @akhil-ambady-ibs
> 
> @kefeh Can you please test this https://pub.dev/packages/no_screenshot/versions/1.0.0-beta.2

@fonkamloic It is not working

**Comment by fonkamloic** [comment]
Can you share the error you are getting?

**Comment by fonkamloic** [comment]
> @
> 
> 
> 
> > @kpitroda @ilyasarafathemvigo @akhil-ambady-ibs
> 
> > 
> 
> > @kefeh Can you please test this https://pub.dev/packages/no_screenshot/versions/1.0.0-beta.2
> 
> 
> 
> @fonkamloic It is not working

Can you share an error or instructions to help me reproduce this?

**Comment by kpitroda** [comment]
> @kpitroda @akhil-ambady-ibs @akhil-ambady-ibs
> 
> Could you please specify what iOS version each of you is using?

iOS version : 17.5.1
Device : iPhone XR

**Comment by fonkamloic** [comment]
> > @kpitroda @akhil-ambady-ibs @akhil-ambady-ibs
> 
> > 
> 
> > Could you please specify what iOS version each of you is using?
> 
> 
> 
> iOS version : 17.5.1
> 
> Device : iPhone XR
> 
> 

What error do you see in your debug console when using v1.0.0-beta.2?

**Comment by kpitroda** [comment]
I'm not testing this in iOS emulator. I have testing this in physical device.

**Comment by fonkamloic** [comment]
You can see any log in the console if you run on a physical device in debug mode. Check if you get any error when you toggle `screenshotOff` 

If any check here

**Comment by ilyasarafathemvigo** [comment]
@fonkamloic 
There is no error in the console 
iOS version : 17.5.1
Model: iPhone 14

**Comment by achego** [comment]
@fonkamloic , same here, it works only the first time, taking screenshot shows a black screen, but subsequently im able to take screen shot, so it got me thinking, do we need to always call the disable screenshot on Applifecycle change

**Comment by fonkamloic** [comment]
On: [1.0.0-beta.2](https://pub.dev/packages/no_screenshot/versions/1.0.0-beta.2)


@achego you are right! After closing the app completely on iOS and restarting. The state is not restored. 
Fixing that...

Let me know if you notice any more issues. I will add it to the next build.

**Comment by fonkamloic** [comment]
@achego here you go [0.3.1](https://pub.dev/packages/no_screenshot/versions/0.3.1)

**Comment by fonkamloic** [comment]
@kefeh I couldn't get your screencast to preview it on pub.dev

**Comment by kefeh** [comment]
> @kefeh I couldn't get your screencast to preview on pub.dev. Apparently, it has to be a gif.
Let me update it asap
