### ISSUE TITLE
chat implemtation

### ISSUE THREAD

**Issue by Curry44424** [FlutterPlaza/no_screenshot#44]
not an issue just wanted to know if this has a chat- feature implementation could be very useful for what I'm building

**Comment by davidCcD** [comment]
what is chat- feature?

**Comment by Curry44424** [comment]
normal chat within flutter application

**Comment by fonkamloic** [comment]
@Curry44424, do you mean a Discord chat to discuss issues? 


If not, please share a sample of your thoughts and how you are currently using this package.
