### ISSUE TITLE
No podspec found for macos

### ISSUE THREAD

**Issue by pandiarajanvp** [FlutterPlaza/no_screenshot#47]
pod install error 

No podspec found for `no_screenshot` in `Flutter/ephemeral/.symlinks/plugins/no_screenshot/macos`

**Comment by Wassiem-Ibrahim** [comment]
I am facing the same issue here

    [!] No podspec found for `no_screenshot` in `Flutter/ephemeral/.symlinks/plugins/no_screenshot/macos`

**Comment by fonkamloic** [comment]
Thank you for your feedback @pandiarajanvp  and @Wassiem-Ibrahim. 

Taking a look

**Comment by AshishDT** [comment]
@fonkamloic 

Have you found any solution ?

**Comment by AshishDT** [comment]
> Thank you for your feedback @pandiarajanvp and @Wassiem-Ibrahim.
> 
> Taking a look

I have one solution try to run this command

flutter create --platforms=macos .

in this package this might solve our issue

**Comment by fonkamloic** [comment]
Try this version https://pub.dev/packages/no_screenshot/versions/0.3.2-beta.1

Unfortunately, I don't think it is possible to prevent screen recording on MacOS or to listen to screenshot events. 
However, the update should prevent screenshots. If you have an idea comment here and I usually respond faster https://x.com/FonkamL/status/1854742126946295982 

cc: @pandiarajanvp @AshishDT @Wassiem-Ibrahim

**Comment by fonkamloic** [comment]
@kefeh, could you please test this?

**Comment by harkairt** [comment]
works for me. 👍

**Comment by fonkamloic** [comment]
Thank you @harkairt ! 

Closing this
