### ISSUE TITLE
An operation is not implemented: Not yet implemented

### ISSUE THREAD

**Issue by felixjunghans** [FlutterPlaza/no_screenshot#5]
Hello I am working with another plugin, which restarts the app at a certain time. Unfortunately the app crashes during the restart because NoScreenshot throws an error. Could you maybe fix the error?

```
 kotlin.NotImplementedError: An operation is not implemented: Not yet implemented
        at com.flutterplaza.no_screenshot.NoScreenshotPlugin.onDetachedFromActivity(NoScreenshotPlugin.kt:81)
```

**Comment by fonkamloic** [comment]
Hello @felixjunghans, thank you for raising this issue. 

How can we reproduce this error? 

I think it is an error due to strict linting rules.

**Comment by felixjunghans** [comment]
So I implemented a function with the package dynamic_icon_flutter 0.0.7 where you can change your app icon. During the change of the app icon, the MainActivity is terminated and a new activity is started. This error occurred during this process. After I removed the lines ("Not yet implemented"), everything ran without problems.

**Comment by fonkamloic** [comment]
Could you please make your pull request to the `development` branch?

**Comment by fonkamloic** [comment]
Thank you for your contribution @felixjunghans, 
We will publish your changes shortly
