### ISSUE TITLE
Do not retract versions in future

### ISSUE THREAD

**Issue by vbuberen** [FlutterPlaza/no_screenshot#52]
Hello there. 

Thanks for this package, but, please, in future do not retract any versions as such action breaks pipelines for projects using the package and creates a negative impression about it.

<img width="555" alt="Screenshot 2024-11-11 at 17 43 09" src="https://github.com/user-attachments/assets/9d19774b-a554-488c-ba18-16e78c877383">

**Comment by fonkamloic** [comment]
Hello @vbuberen,

Thank you for your feedback. We did not plan on making that change. Unfortunately, there was an issue with the versioning. The latest version was supposed to be 0.3.X, which caused the updates to the package to not reflect as the latest.

We appreciate your time in bringing this issue to our attention, and please know that your feedback has been taken seriously.
